name: job-auto-fill
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - selenium=4.15.2
  - webdriver-manager=4.0.1
  - pyperclip=1.8.2
  - requests>=2.25.0
  - pip
  - pip:
    - keyboard==0.13.5
    - tkinter-tooltip==2.0.0
    - packaging>=20.0 